// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtT2MZ-pmzXpC7n4EtlFfFqHN2TopSX_E',
    appId: '1:830327029793:web:973d7ab686564d7df7e360',
    messagingSenderId: '830327029793',
    projectId: 'my-store-79012',
    authDomain: 'my-store-79012.firebaseapp.com',
    storageBucket: 'my-store-79012.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3EQXK37eQsxtWcXd3NB-WRnU12ur5h5I',
    appId: '1:830327029793:android:00a487e1f0e4853af7e360',
    messagingSenderId: '830327029793',
    projectId: 'my-store-79012',
    storageBucket: 'my-store-79012.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMDejlVEdlrXZMvCjVNMcl40kMgW3gmys',
    appId: '1:830327029793:ios:e41ab4051fc5f1e9f7e360',
    messagingSenderId: '830327029793',
    projectId: 'my-store-79012',
    storageBucket: 'my-store-79012.appspot.com',
    iosBundleId: 'com.example.multiVendorAppProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMDejlVEdlrXZMvCjVNMcl40kMgW3gmys',
    appId: '1:830327029793:ios:e41ab4051fc5f1e9f7e360',
    messagingSenderId: '830327029793',
    projectId: 'my-store-79012',
    storageBucket: 'my-store-79012.appspot.com',
    iosBundleId: 'com.example.multiVendorAppProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtT2MZ-pmzXpC7n4EtlFfFqHN2TopSX_E',
    appId: '1:830327029793:web:216f65fcef870ae4f7e360',
    messagingSenderId: '830327029793',
    projectId: 'my-store-79012',
    authDomain: 'my-store-79012.firebaseapp.com',
    storageBucket: 'my-store-79012.appspot.com',
  );
}
